baseURL = 'http://luxkao.me'
languageCode = 'en-us'
title = 'luxkao'
theme = 'my-theme'

 [menu]
    [[menu.main]]   
    identifier = 'blog'
    name = 'blog'
    url = '/blog'
    weight = '1'

    [[menu.main]]   
    identifier = 'github'
    name = 'github'
    url = 'https://github.com/luxkao'
    weight = '5'

   [params]
      nextprev = true